#!/bin/sh

path_templates=templates/*.html
active_jshint_validation=1

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [ "$files" = "" ];
then
    exit 0
fi

rand=$(git rev-parse HEAD)

for file in ${files};
do
    if [ $active_jshint_validation -eq 1 ];
    then
        echo "Jshint validation"
        errors=0

        jshint ${file}
        errors=$((${errors} + $?))

        if [ $errors -ne 0 ];
        then
            echo "JSHint detected syntax problems"
            echo "Commit aborted"

            exit $errors
        fi
    fi

    echo "Add number version for static file"
    new_name=${file}'?version='$rand

    for temp_file in $path_templates
    do
        sed -i "s;$file\(?version=[a-zA-Z0-9]*\)\?;$new_name;g" $temp_file
        git add $temp_file
    done
done
