#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [ "$files" = "" ];
then
    exit 0
fi

rand=$(git rev-parse HEAD)
#rand=$(tr -cd 0-9 </dev/urandom | head -c 3)

for file in ${files};
do
    echo "Add number version for static file"

    new_name=${file}'?version='$rand

    echo $(git rev-parse HEAD)

    for temp_file in templates/*.html
    do
        sed -i "s;$file\(?version=[0-9]*\)\?;$new_name;g" $temp_file
        git add $temp_file
    done
done